import { Food } from "./app/shared/models/Food";



export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-15',
    price: 10,
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/pizza.jpg',
    tags: ['Fast Food', 'pizza', 'italian'],
  },
  {
    id:'2',
    name: 'Steak',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Florence', 'Italy'],
    stars: 4.7,
    imageUrl: 'assets/steak.jpg',
    tags: ['steak', 'bbq', 'meat', 'Main Course'],
  },
  {
    id:'3',
    name: 'Classic Burger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Germany', 'US'],
    stars: 3.5,
    imageUrl: 'assets/burger.jpg',
    tags: ['Fast Food', 'Hamburger', 'Burger', 'Meat'],
  },
  {
    id:'4',
    name: 'Ribs',
    price: 25,
    cookTime: '20-40',
    favorite: true,
    origins: ['Carraibe'],
    stars: 3.3,
    imageUrl: 'assets/ribs.jpg',
    tags: ['meat', 'ribs', 'bbq', 'grill', 'Main Course'],
  },
  {
    id:'5',
    name: 'Shrimps',
    price: 30,
    cookTime: '10-20',
    favorite: false,
    origins: ['South Africa', 'Africa'],
    stars: 3.0,
    imageUrl: 'assets/shrimps.jpg',
    tags: ['seafood', 'shrimps', 'fish', 'Main Course'],
  },
  {
    id: '6',
    name: 'Pizza Margherita',
    price: 15,
    cookTime: '12-15',
    favorite: true,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/pizza_margherita.jpg',
    tags: ['pizza', 'italian', 'Fast Food'],
  },
  {
    id: '7',
    name: 'Caesar Salad',
    price: 12,
    cookTime: '10-12',
    favorite: false,
    origins: ['Mexico'],
    stars: 4.0,
    imageUrl: 'assets/caesar_salad.jpg',
    tags: ['salad', 'appetizer', 'vegetarian', 'Main Course'],
  },
  {
    id: '8',
    name: 'Sushi Platter',
    price: 35,
    cookTime: '15-30',
    favorite: true,
    origins: ['Japan'],
    stars: 4.8,
    imageUrl: 'assets/sushi_platter.jpg',
    tags: ['sushi', 'japanese', 'seafood', 'Main Course','fish'],
  },
  {
    id: '9',
    name: 'Classic Cheesecake',
    price: 10,
    cookTime: '15-30',
    favorite: true,
    origins: ['United States'],
    stars: 4.7,
    imageUrl: 'assets/classic_cheesecake.jpg',
    tags: ['Dessert', 'cheesecake', 'classic', 'sweet'],
  },
  {
    id: '10',
    name: 'Vegetarian Supreme Pizza',
    cookTime: '15-20',
    price: 14,
    favorite: false,
    origins: ['International'],
    stars: 4.6,
    imageUrl: 'assets/vegetarian_pizza.jpg',
    tags: ['Fast Food', 'pizza', 'vegetarian'],
  },
  {
    id: '11',
    name: 'Cheeseburger',
    cookTime: '8-12',
    price: 8,
    favorite: true,
    origins: ['United States'],
    stars: 4.5,
    imageUrl: 'assets/cheeseburger.jpg',
    tags: ['Fast Food', 'burger', 'american', 'cheeseburger'],
  },
  {
    id: '12',
    name: 'Beef Burger',
    cookTime: '10-15',
    price: 9,
    favorite: false,
    origins: ['International'],
    stars: 4.3,
    imageUrl: 'assets/beef_burger.jpg',
    tags: ['Fast Food', 'burger', 'worldwide'],
  }
 
 
 




]