import { Food } from "./app/shared/models/Food";



export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-15',
    price: 10,
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/pizza.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch', 'italian'],
  },
  {
    id:'2',
    name: 'Steak',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Florence', 'Italy'],
    stars: 4.7,
    imageUrl: 'assets/steak.jpg',
    tags: ['steak', 'Lunch', 'BBQ', 'meat', 'main course'],
  },
  {
    id:'3',
    name: 'Classic Burger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Germany', 'US'],
    stars: 3.5,
    imageUrl: 'assets/burger.jpg',
    tags: ['FastFood', 'Hamburger', 'Burger', 'Meat'],
  },
  {
    id:'4',
    name: 'Ribs',
    price: 25,
    cookTime: '20-40',
    favorite: true,
    origins: ['Carraibe'],
    stars: 3.3,
    imageUrl: 'assets/ribs.jpg',
    tags: ['meat', 'ribs', 'bbq', 'grill', 'main course'],
  },
  {
    id:'5',
    name: 'Shrimps',
    price: 30,
    cookTime: '10-20',
    favorite: false,
    origins: ['South Africa', 'Africa'],
    stars: 3.0,
    imageUrl: 'assets/shrimps.jpg',
    tags: ['seafood', 'shrimps', 'fish'],
  },
  {
    id: '6',
    name: 'Pizza Margherita',
    price: 15,
    cookTime: '12-15',
    favorite: true,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'assets/pizza_margherita.jpg',
    tags: ['pizza', 'italian', 'fast food'],
  },
  {
    id: '7',
    name: 'Caesar Salad',
    price: 12,
    cookTime: '10-12',
    favorite: false,
    origins: ['Mexico'],
    stars: 4.0,
    imageUrl: 'assets/caesar_salad.jpg',
    tags: ['salad', 'appetizer', 'vegetarian'],
  },
  {
    id: '8',
    name: 'Sushi Platter',
    price: 35,
    cookTime: '15-30',
    favorite: true,
    origins: ['Japan'],
    stars: 4.8,
    imageUrl: 'assets/sushi_platter.jpg',
    tags: ['sushi', 'japanese', 'seafood', 'main course','fish'],
  },
  {
    id: '9',
    name: 'Classic Cheesecake',
    price: 10,
    cookTime: '15-30',
    favorite: true,
    origins: ['United States'],
    stars: 4.7,
    imageUrl: 'assets/classic_cheesecake.jpg',
    tags: ['dessert', 'cheesecake', 'classic', 'sweet'],
}




]